apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
  labels:
    type: local
    name: mysql-storage
spec:
  storageClassName: mysql-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    type: DirectoryOrCreate
    path: /mnt/mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-persistent-storage
  labels:
    type: local
    name: influxdb-storage
spec:
  storageClassName: influxdb-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    type: DirectoryOrCreate
    path: /mnt/influxdb
