apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:ft_services
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.102
  selector:
    app: wordpress
  ports:
  - port: 5050
    name: port-http
    protocol: TCP
    targetPort: 5050
