apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - port: 5050
    name: http
    protocol: TCP
    targetPort: 5050
  selector:
    app: wordpress
  type: LoadBalancer
  loadBalancerIP: 192.168.99.20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress_alpine
        name: wordpress
        imagePullPolicy: Never
