apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  ports:
  - port: 21
    name: http
    protocol: TCP
    targetPort: 21
  - port: 21021
    name: passv
    protocol: TCP
    targetPort: 21021
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.50
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pv-claim
  labels:
    app: ftps
spec:
  storageClassName: ftps-storage
  selector:
    matchLabels:
      name: ftps-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps_alpine
        name: ftps
        imagePullPolicy: Never
        lifecycle:
          postStart:
            exec:
              command:
                - "chown"
                - "user"
                - "/ftp"
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /ftp
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim
