apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  ports:
  - port: 21
    name: http
    protocol: TCP
    targetPort: 21
  - port: 21021
    name: passv
    protocol: TCP
    targetPort: 21021
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps_alpine
        name: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 21021
